"""Regenerate the committed ``ase_db`` golden fixtures (M55-S1; Part 8 §3).

``.db`` is ASE's SQLite database container, so — like the ``.traj`` ULM fixtures — the golden
source bytes cannot be authored by hand. This script builds each case's rows from exactly the
values the expectation records, writes the deterministic ``.db`` bytes (SQLite output is
byte-deterministic for a fixed sequence of writes: no timestamps in the page data — verified
below), parses them through the real parser to emit ``expected.canonical.json``, and writes each
``manifest.yaml`` with the two SHA-256 digests it must carry.

The expectations are still *external truth*, not a blind snapshot: every value fed to ``Atoms``
here is an exact, hand-chosen quantity (integer-ish coordinates, isotope masses, round
energies), so each number in ``expected.canonical.json`` is one a reader can verify by eye
against the rows built below. Run from the repo root::

    python tests/golden/ase_db/_generate.py

then commit the regenerated ``sample.db`` / ``expected.canonical.json`` / ``manifest.yaml`` if the
fixtures changed. This module is governance *scaffolding* (a ``.py`` file), so the corpus coverage
check ignores it.
"""

from __future__ import annotations

import hashlib
import io
import tempfile
from collections.abc import Callable, Iterator
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path
from unittest import mock

import ase.db.row as ase_db_row
import ase.db.sqlite as ase_db_sqlite
import numpy as np
from ase import Atoms
from ase.calculators.singlepoint import SinglePointCalculator
from ase.constraints import FixAtoms
from ase.db import connect

from xtalate.parsers.ase_db import make_ase_db_parser

HERE = Path(__file__).parent

Row = tuple[Atoms, dict[str, object], dict[str, object]]


class _FixedUUID:
    """A counter-based stand-in for ``uuid.uuid4()`` so committed ``.db`` bytes are reproducible.

    ASE stamps every row with ``uuid.uuid4().hex`` plus a wall-clock ``ctime``/``mtime`` and the
    ``$USER`` env var — the very manufactured metadata the parser launders back to absence (P3).
    Left alone they make the SQLite bytes differ on every run; pinning them here is what lets the
    fixture be regenerated byte-identically (and lets ``_write_db_bytes`` assert that). The counter
    keeps distinct rows distinct without reintroducing randomness."""

    def __init__(self) -> None:
        self._n = 0

    def uuid4(self) -> _FixedUUID:
        self._n += 1
        return self

    @property
    def hex(self) -> str:
        return f"{self._n:032x}"


@contextmanager
def _deterministic() -> Iterator[None]:
    """Pin ASE's three non-deterministic row-metadata sources for reproducible fixture bytes."""
    with (
        mock.patch.object(ase_db_row, "uuid", _FixedUUID()),
        mock.patch.object(ase_db_sqlite, "now", lambda: 0.0),
        mock.patch.dict("os.environ", {"USER": "xtalate-golden"}),
    ):
        yield


@dataclass(frozen=True)
class Case:
    build: Callable[[], list[Row]]
    notes: str


def _single_row_labeled() -> list[Row]:
    """Rich all-fields row: a CO molecule with a cell + pbc, source-written (isotope) masses,
    velocities, initial charges/magmoms, a FixAtoms constraint, a key-value pair, and a
    calculator energy + forces. Exercises every mapped canonical field in one fixture."""
    atoms = Atoms(
        symbols=["C", "O"],
        positions=[[0.0, 0.0, 0.0], [0.0, 0.0, 1.10]],
        cell=[6.0, 6.0, 6.0],
        pbc=True,
    )
    atoms.set_masses([12.011, 15.999])
    atoms.set_velocities(np.full((2, 3), 0.01))
    atoms.set_initial_charges([0.3, -0.3])
    atoms.set_initial_magnetic_moments([0.0, 1.0])
    atoms.set_constraint(FixAtoms(indices=[0]))
    atoms.calc = SinglePointCalculator(atoms, energy=-5.0, forces=np.full((2, 3), 0.01))
    return [(atoms, {"label": "co-relaxed"}, {"note": [1, 2]})]


def _rich_key_value() -> list[Row]:
    """Minimal molecule + key-value anchor: one bare water frame (ASE's manufactured defaults
    — zero cell, derived masses, zeroed momenta, generated id/ctime/mtime/user, empty kv —
    must all launder to absence) plus a rich key-value pair set and a data blob, the
    carry-never-interpret Part 2 §6.1 surface."""
    atoms = Atoms(
        symbols=["H", "O", "H"],
        positions=[[0.0, 0.0, 0.0], [0.0, 0.0, 0.98], [0.0, 0.93, -0.26]],
    )
    return [
        (atoms, {"kind": "water", "charge": 0.0, "steps": 3, "done": True}, {"blob": [1, 2, 3]})
    ]


CASES: dict[str, Case] = {
    "single-row-labeled": Case(
        build=_single_row_labeled,
        notes=(
            "The all-fields anchor: a single labeled CO row carrying a present cell + pbc, "
            "source-written isotope masses, velocities, initial charges/magmoms, a FixAtoms "
            "constraint, and a SinglePointCalculator energy + forces. Proves that nothing the "
            "source *did* state is laundered away, and that a per-row key-value pair + data blob "
            "carry verbatim into user_metadata.custom_global under the ase_db: namespace "
            "(carry-never-interpret, Part 2 §6.1) with ASEDB_KV_CARRIED warnings. A single row "
            "is one Canonical Object, never a trajectory (a dataset is aggregation, not a new "
            "model): trajectory launders to None."
        ),
    ),
    "rich-key-value": Case(
        build=_rich_key_value,
        notes=(
            "The minimal-molecule + laundering anchor: one bare water row with only symbols and "
            "positions. ASE always hands back a fully-populated Atoms, so this fixture proves the "
            "parser launders every manufactured default back to absence (P3) on a *real "
            "committed* file — the all-zero 3x3 cell -> None, Z-derivable masses -> None, zeroed "
            "momenta -> dynamics.velocities None, the empty constraints list -> None, and ASE's "
            "generated id/ctime/mtime/user + empty kv dict -> absent. The rich key-value set and "
            "data blob still carry into user_metadata.custom_global (carry, never interpret)."
        ),
    ),
}


def _write_db_bytes(rows: list[Row]) -> bytes:
    with tempfile.NamedTemporaryFile(suffix=".db") as tmp, _deterministic():
        db = connect(tmp.name, use_lock_file=False)
        for atoms, kv, data in rows:
            db.write(atoms, key_value_pairs=kv, data=data)
        tmp.flush()
        return Path(tmp.name).read_bytes()


_MANIFEST = """\
case: {case}
format_id: ase_db
source_file: sample.db
expected_canonical: expected.canonical.json
canonical_schema_version: "1.0.0"
sha256: "{sha256}"
expected_sha256: "{expected_sha256}"
origin:
  kind: synthetic
  source: >-
    Hand-authored for M55-S1 via tests/golden/ase_db/_generate.py (ASE .db SQLite container).
  license: "Apache-2.0"
notes: >-
  {notes}
"""


def _generate_case(case: str, spec: Case) -> None:
    rows = spec.build()
    source = _write_db_bytes(rows)
    # SQLite output must be byte-deterministic for a committed fixture to be reproducible.
    if source != _write_db_bytes(spec.build()):
        raise AssertionError(f"{case}: .db bytes are not reproducible")

    directory = HERE / case
    directory.mkdir(exist_ok=True)
    (directory / "sample.db").write_bytes(source)

    obj = make_ase_db_parser().parse(io.BytesIO(source), filename="sample.db").canonical
    expected = obj.model_dump_json(indent=2) + "\n"
    (directory / "expected.canonical.json").write_text(expected, encoding="utf-8")

    manifest = _MANIFEST.format(
        case=case,
        sha256=hashlib.sha256(source).hexdigest(),
        expected_sha256=hashlib.sha256(expected.encode()).hexdigest(),
        notes=" ".join(spec.notes.split()),
    )
    (directory / "manifest.yaml").write_text(manifest, encoding="utf-8")
    print(f"{case}: wrote sample.db + expected.canonical.json + manifest.yaml")


if __name__ == "__main__":
    for case, spec in CASES.items():
        _generate_case(case, spec)
