"""Stage 4 of the CIF reader: validated document → Canonical Object (DECISIONS.md D65).

The only stage that knows ``xtalate.schema`` exists. Everything requiring canonical knowledge
lives here: the element table, unit conventions, the fractional→Cartesian conversion, and the
absence convention (**P3**).

Two format-defined facts are recorded in ``parse_notes`` rather than guessed (Part 3 §5 rule 3):
full 3-D periodicity, which CIF implies by describing a crystal and never states as a tag
(§3 n.3), and the coordinate conversion itself. Nothing else is added to the structure.
"""

from __future__ import annotations

import math
import re
from fractions import Fraction
from typing import Any

import numpy as np

from xtalate.parsers._common import build_provenance
from xtalate.parsers.cif._document import CifBlock, CifLoop
from xtalate.parsers.cif._symmetry import (
    MERGE_THRESHOLD_ANGSTROM,
    Expansion,
    SymmetryOperation,
    expand_sites,
)
from xtalate.parsers.cif._validate import (
    CELL_ANGLE_TAGS,
    CELL_LENGTH_TAGS,
    FRACT_TAGS,
    LABEL_TAG,
    OCCUPANCY_TAG,
    SPACE_GROUP_NAME_TAGS,
    TYPE_SYMBOL_TAG,
    has_uncertainty,
    parse_number,
    validate_atom_sites,
    validate_cell,
    validate_oxidation_numbers,
    validate_symmetry,
)
from xtalate.schema import (
    AtomsBlock,
    CanonicalObject,
    Cell,
    Electronic,
    Frame,
    SimulationMetadata,
    UserMetadata,
)
from xtalate.schema.elements import is_valid_symbol
from xtalate.schema.paths import OCCUPANCY_CUSTOM_KEY, is_full_occupancy
from xtalate.sdk import ParseError, ParseIssue

_PBC_NOTE = (
    "pbc set to (true,true,true): a CIF describes a crystal, so full 3-D periodicity is "
    "format-defined (Part 3 §3 n.3), not assumed."
)
_FRACTIONAL_NOTE = (
    "Fractional coordinates converted to Cartesian using the lattice matrix built from "
    "_cell_length_* / _cell_angle_* (Part 2 §4)."
)
_CARTESIAN_NOTE = "Cartesian _atom_site_Cartn_* coordinates read verbatim in Å (Part 2 §4)."
_EXPANSION_NOTE = (
    "Symmetry expansion: {sites} declared site(s) expanded to {atoms} atom(s) by applying the "
    "{operations} symmetry operation(s) the file declares (Part 3 §3 n.13). Per-site "
    "multiplicities: {multiplicities}. {merged} coincident image(s) were merged as special "
    "positions within {threshold} Å (DECISIONS.md D67). Coordinates generated by an operation "
    "were wrapped into the unit cell; declared coordinates are carried as the file spelled them."
)
#: Where partial site occupancy lands. The Canonical Model has no first-class occupancy field
#: (Part 3 §3 n.11 — the known schema gap and a Part 2 §6 rule-4 promotion candidate), so the
#: column is carried verbatim under the key the spec names. It is the one ``_atom_site`` column
#: whose custom key is not its tag spelling: occupancy is a *named* limitation with a documented
#: promotion path, so the key it will be promoted from is pinned — in ``schema.paths``, since the
#: layers that must recognise occupancy without knowing anything about CIF read it from there.
OCCUPANCY_KEY = OCCUPANCY_CUSTOM_KEY
#: The label for what ``electronic.charges`` holds when it came from a CIF. The canonical field
#: is a net per-atom charge in e; a formal oxidation state is an integer bookkeeping convention,
#: not a computed population analysis, and conflating the two would let a downstream consumer
#: read an idealized +3 as a Mulliken charge.
CHARGE_SCHEME_KEY = "cif:charge_scheme"
CHARGE_SCHEME = "formal_oxidation_state"

_OCCUPANCY_NOTE = (
    "occupancy carried as a custom per-atom array: the file declares _atom_site_occupancy and "
    "the Canonical Model has no occupancy field, so the column is preserved verbatim in "
    f"user_metadata.custom_per_atom[{OCCUPANCY_KEY!r}] rather than modelled (Part 3 §3 n.11). "
    "Only the CIF target can write it back."
)
_PARTIAL_OCCUPANCY_NOTE = (
    "partial site occupancy: {partial} of {total} sites declare an occupancy that is not 1 "
    "(unknown values, '?' or '.', count as not-1 — silence is not a claim of fullness). The "
    "structure carries a whole atom at every such site, so its composition is the fully-occupied "
    "one and does not equal the file's own _chemical_formula_sum. CIF is the only Phase 1 target "
    "that writes the column back; converting to any other target discards the distinction."
)
_CHARGE_NOTE = (
    "electronic.charges populated from the formal oxidation states the file declares in its "
    "_atom_type_oxidation_number loop, joined to the sites by _atom_site_type_symbol. These are "
    "integer bookkeeping charges, not a computed population analysis; the scheme is labelled "
    f"{CHARGE_SCHEME!r} in simulation.extra[{CHARGE_SCHEME_KEY!r}]."
)
_UNCERTAINTY_NOTE_PREFIX = (
    "source values carried a parenthesized standard uncertainty, which was read as the value "
    "and whose precision digits are not modelled: "
)

# Structural _atom_site columns the builder maps to canonical fields. Every *other* column in
# the loop is carried verbatim into custom_per_atom, so a tag this version does not understand
# (occupancy, Wyckoff symbols, displacement parameters) is preserved rather than dropped (P1).
_CONSUMED_SITE_TAGS = frozenset(
    {
        TYPE_SYMBOL_TAG,
        "_atom_site_fract_x",
        "_atom_site_fract_y",
        "_atom_site_fract_z",
        "_atom_site_cartn_x",
        "_atom_site_cartn_y",
        "_atom_site_cartn_z",
        # Not mapped to a canonical field either, but placed under its own spec-named key
        # (OCCUPANCY_KEY) with its own warning, so it is excluded from the generic carry to
        # keep one source column from arriving under two names.
        OCCUPANCY_TAG,
    }
)

# An element symbol with an optional oxidation-state suffix: "Fe", "Fe3+", "O2-", "Ca+".
_TYPE_SYMBOL = re.compile(r"^([A-Za-z]{1,2})(\d*[+-]|[+-]\d*)?$")
# A site label: element letters followed by an arbitrary site index — "O1", "Fe2A", "Ca1_2".
_LABEL = re.compile(r"^([A-Za-z]{1,2})[0-9_].*$|^([A-Za-z]{1,2})$")


def _error(code: str, message: str, *, location: str | None = None) -> ParseError:
    return ParseError([ParseIssue(severity="error", code=code, message=message, location=location)])


_SQRT3_OVER_2 = math.sqrt(3.0) / 2.0
# The cell angles crystallography states *exactly*: the right angle of every non-triclinic
# system, and the 30/60/120/150° angles of the hexagonal and rhombohedral ones. libm evaluates
# cos(radians(90)) as 6.1e-17 rather than 0, so a lattice built through it is both spuriously
# non-orthogonal — a 1e-16 tilt the source never declared, which P1 has no business inventing —
# and machine-dependent in its last bit, since the platform's libm, not IEEE 754, decides that
# digit. Both problems disappear by using the exact value the angle actually denotes.
_EXACT_COS_SIN_DEG: dict[float, tuple[float, float]] = {
    30.0: (_SQRT3_OVER_2, 0.5),
    60.0: (0.5, _SQRT3_OVER_2),
    90.0: (0.0, 1.0),
    120.0: (-0.5, _SQRT3_OVER_2),
    150.0: (-_SQRT3_OVER_2, 0.5),
}


def _cos_sin_deg(degrees: float) -> tuple[float, float]:
    """``(cos, sin)`` of an angle in degrees, exact for the standard crystallographic angles."""
    exact = _EXACT_COS_SIN_DEG.get(degrees)
    if exact is not None:
        return exact
    radians = math.radians(degrees)
    return math.cos(radians), math.sin(radians)


def lattice_from_parameters(
    lengths: tuple[float, float, float], angles: tuple[float, float, float]
) -> np.ndarray:
    """Build the 3×3 lattice matrix (rows a, b, c, in Å) from cell parameters.

    CIF is the only Phase 1 format that states a cell as *parameters* rather than vectors, so
    an orientation convention has to be chosen; a≈+x with b in the xy half-plane is the
    crystallographic standard and is documented here because it is otherwise invisible. The
    choice is not observable in any physical quantity — lengths, angles, volume and all
    interatomic distances are rotation-invariant — but it *is* observable in the exported
    Cartesian coordinates, which is why it is pinned rather than left to floating-point luck.
    """
    a, b, c = lengths
    cos_alpha, _ = _cos_sin_deg(angles[0])
    cos_beta, _ = _cos_sin_deg(angles[1])
    cos_gamma, sin_gamma = _cos_sin_deg(angles[2])

    cx = c * cos_beta
    cy = c * (cos_alpha - cos_beta * cos_gamma) / sin_gamma
    cz_squared = c * c - cx * cx - cy * cy
    if cz_squared <= 0.0:
        raise _error(
            "CIF_INVALID_CELL",
            f"cell angles alpha={angles[0]}, beta={angles[1]}, gamma={angles[2]} do not "
            "describe a realizable cell (the implied volume is zero or negative)",
        )
    return np.asarray(
        [
            [a, 0.0, 0.0],
            [b * cos_gamma, b * sin_gamma, 0.0],
            [cx, cy, math.sqrt(cz_squared)],
        ],
        dtype=float,
    )


def element_of(raw_type: str | None, raw_label: str | None, *, line: int) -> str:
    """The element symbol for one site, laundered from its type symbol or label.

    ``_atom_site_type_symbol`` is preferred and carries an optional oxidation-state suffix
    (``Fe3+``); the charge part is split off here and the *raw* symbol is carried verbatim into
    ``custom_per_atom`` so M19 can reconcile it against ``_atom_type_oxidation_number`` without
    re-reading the file. Falling back to ``_atom_site_label`` (``O1``, ``Fe2A``) is a genuine
    reading of the format, not a guess — the label's leading letters are its element by CIF
    convention — but an unrecognizable one is an error, never a placeholder element.
    """
    for raw, pattern in ((raw_type, _TYPE_SYMBOL), (raw_label, _LABEL)):
        if raw is None:
            continue
        match = pattern.match(raw.strip())
        if match is None:
            continue
        symbol = next(g for g in match.groups() if g)
        symbol = symbol[0].upper() + symbol[1:].lower()
        if is_valid_symbol(symbol):
            return symbol
    raise _error(
        "CIF_INVALID_SYMBOL",
        f"cannot identify an element from type symbol {raw_type!r} / label {raw_label!r}; "
        "symbols are required and are never invented (Part 2 §3.3)",
        location=f"line {line}",
    )


def build(
    block: CifBlock, *, format_id: str, filename: str | None, parser_version: str
) -> tuple[CanonicalObject, list[ParseIssue]]:
    """Assemble the Canonical Object for one validated ``data_`` block."""
    issues: list[ParseIssue] = []
    lengths, angles, cell_uncertain = validate_cell(block)
    space_group, operations = validate_symmetry(block)
    loop, coord_tags, fractional = validate_atom_sites(block)
    oxidation_numbers = validate_oxidation_numbers(block)

    lattice = lattice_from_parameters(lengths, angles)
    coords, coord_uncertain = _coordinates(loop, coord_tags)
    uncertain = coord_uncertain | cell_uncertain

    expansion = _expand(coords, operations, lattice=lattice, fractional=fractional, loop=loop)
    if expansion is not None:
        coords = np.asarray(
            [[float(value) for value in site] for site in expansion.coordinates], dtype=float
        )
    positions = coords @ lattice if fractional else coords

    # Every per-site fact — element, occupancy, label — belongs to the atoms its declared site
    # generated, so each is replicated through the same source_index mapping.
    site_of = expansion.source_index if expansion is not None else tuple(range(len(loop.rows)))
    types = loop.column(TYPE_SYMBOL_TAG)
    labels = loop.column(LABEL_TAG)
    symbols = [
        element_of(
            types[i] if types is not None else None,
            labels[i] if labels is not None else None,
            line=loop.line,
        )
        for i in site_of
    ]

    custom_per_atom: dict[str, Any] = {
        key: [column[i] for i in site_of] for key, column in _carried_columns(loop).items()
    }
    if types is not None:
        # Preserved even though it was consumed: the oxidation-state suffix is real source
        # information the element symbol alone does not carry, and it is what the declared
        # oxidation numbers join against below.
        custom_per_atom["cif:type_symbol"] = [types[i] for i in site_of]

    occupancy = loop.column(OCCUPANCY_TAG)
    partial_note: str | None = None
    if occupancy is not None:
        carried_occupancy = [occupancy[i] for i in site_of]
        custom_per_atom[OCCUPANCY_KEY] = carried_occupancy
        issues.append(
            ParseIssue(
                severity="warning",
                code="CIF_OCCUPANCY_NOT_MODELLED",
                message=_OCCUPANCY_NOTE,
                location=f"line {loop.line}",
            )
        )
        # Two separate facts, deliberately two separate codes. That the column exists at all is a
        # schema gap and is reported whenever it appears (M19's plan of record). That some site is
        # *actually* partial is a statement about this structure's chemistry, and it is the one a
        # reader needs: COD writes an occupancy column on nearly every entry, so a single code
        # covering both would fire on almost every real file while saying nothing about which
        # ones hold real disorder — and a warning that cries wolf on the common case trains its
        # reader to skim past the rare one that matters.
        partial = sum(1 for value in carried_occupancy if not is_full_occupancy(value))
        if partial:
            partial_note = _PARTIAL_OCCUPANCY_NOTE.format(
                partial=partial, total=len(carried_occupancy)
            )
            issues.append(
                ParseIssue(
                    severity="warning",
                    code="CIF_PARTIAL_OCCUPANCY",
                    message=partial_note,
                    location=f"line {loop.line}",
                )
            )

    charges, charge_issues = _charges(oxidation_numbers, types, site_of, line=loop.line)
    issues.extend(charge_issues)

    parse_notes = [_FRACTIONAL_NOTE if fractional else _CARTESIAN_NOTE, _PBC_NOTE]
    if expansion is not None:
        parse_notes.append(
            _EXPANSION_NOTE.format(
                sites=len(loop.rows),
                atoms=len(expansion.coordinates),
                operations=len(operations),
                multiplicities=list(expansion.multiplicity),
                merged=expansion.merged,
                threshold=MERGE_THRESHOLD_ANGSTROM,
            )
        )
    if occupancy is not None:
        parse_notes.append(_OCCUPANCY_NOTE)
    if partial_note is not None:
        parse_notes.append(partial_note)
    if charges is not None:
        parse_notes.append(_CHARGE_NOTE)
    if uncertain:
        parse_notes.append(f"{_UNCERTAINTY_NOTE_PREFIX}{sorted(uncertain)}")
    source_units = {
        "positions": "fractional" if fractional else "angstrom",
        "lattice_vectors": "angstrom",
    }

    extra, carried = _carried_pairs(block)
    if charges is not None:
        extra[CHARGE_SCHEME_KEY] = CHARGE_SCHEME
    if operations:
        # The operations verbatim, one per line: `extra` is dict[str, str], and a CIF operation
        # contains commas, so a newline is the only separator that cannot be confused with the
        # content. What the file declared is recoverable from the output, not just its effect.
        extra["cif:symmetry_operations"] = "\n".join(op.text for op in operations)
    if carried:
        issues.append(
            ParseIssue(
                severity="warning",
                code="CIF_TAGS_CARRIED",
                message=(
                    f"{len(carried)} CIF tag(s) have no canonical field and were carried "
                    f"verbatim into simulation.extra under 'cif:' keys: {sorted(carried)}"
                ),
                location=f"line {block.line}",
            )
        )

    frame = Frame(
        index=0,
        atoms=AtomsBlock(symbols=symbols, positions=positions),
        cell=Cell(lattice_vectors=lattice, pbc=(True, True, True), space_group=space_group),
        electronic=Electronic(charges=charges),
    )
    canonical = CanonicalObject(
        frames=[frame],
        trajectory=None,  # a CIF block is one structure, not a time series (§3.2)
        simulation=SimulationMetadata(extra=extra) if extra else None,
        provenance=build_provenance(
            format_id=format_id,
            filename=filename,
            original_coordinate_system="fractional" if fractional else "cartesian",
            source_units=source_units,
            parse_notes=parse_notes,
            parser_version=parser_version,
        ),
        user_metadata=UserMetadata(
            custom_global={"cif:data_block_name": block.name},
            custom_per_atom=custom_per_atom,
        ),
    )
    return canonical, issues


def _expand(
    coords: np.ndarray,
    operations: list[SymmetryOperation],
    *,
    lattice: np.ndarray,
    fractional: bool,
    loop: CifLoop,
) -> Expansion | None:
    """Apply the declared operations, or ``None`` if the file declares none.

    Symmetry operations are defined on *fractional* coordinates — ``x,y,z`` names the fractional
    axes — so a file that gives Cartesian sites and declares a non-trivial operation list states
    something this parser cannot carry out without inverting the lattice and reinterpreting
    coordinates it was handed in another basis. That is refused rather than approximated: the
    milestone's whole point is that a wrong atom count never leaves this parser quietly.
    """
    if not operations:
        return None
    if not fractional and not all(op.is_identity for op in operations):
        raise _error(
            "CIF_CARTESIAN_SITES_WITH_SYMMETRY",
            f"file declares {len(operations)} symmetry operations but gives its atom sites as "
            "Cartesian _atom_site_Cartn_* coordinates. Symmetry operations are defined on "
            "fractional coordinates, so the declared operations cannot be applied to these "
            "sites; the file is refused rather than expanded on a basis it did not use",
            location=f"line {loop.line}",
        )
    # Exact rationals from the parsed floats: the operations' own translations are exact
    # (`Fraction`), so the expansion arithmetic introduces no error of its own beyond the
    # decimal→binary conversion the source coordinates already carry.
    sites = [(Fraction(row[0]), Fraction(row[1]), Fraction(row[2])) for row in coords]
    rows = tuple(tuple(float(v) for v in vector) for vector in lattice)
    return expand_sites(sites, operations, lattice=rows)  # type: ignore[arg-type]


def charge_of_type_symbol(raw: str) -> float | None:
    """The charge a type symbol's oxidation-state suffix spells — ``Fe3+`` → ``+3.0``.

    ``None`` when the symbol carries no suffix (``Fe``), which is *absence of a statement*, not a
    declaration of neutrality: an unsuffixed symbol is simply how most CIFs name an element.
    """
    match = _TYPE_SYMBOL.match(raw.strip())
    if match is None:
        return None
    suffix = match.group(2)
    if not suffix:
        return None
    sign = -1.0 if "-" in suffix else 1.0
    digits = suffix.strip("+-")
    # A bare "+" / "-" is CIF's spelling of a unit charge; "3+" and "+3" both occur in the wild.
    return sign * (float(digits) if digits else 1.0)


def _charges(
    oxidation_numbers: dict[str, float],
    types: list[str | None] | None,
    site_of: tuple[int, ...],
    *,
    line: int,
) -> tuple[np.ndarray | None, list[ParseIssue]]:
    """Per-atom formal charges from the declared oxidation numbers, or ``None``.

    ``electronic.charges`` is an all-or-nothing per-atom array, so a file declaring oxidation
    numbers for *some* of its atom types cannot populate it: the atoms left over would need a
    fill value, and choosing 0.0 would assert neutrality the file never stated (**P4**). Such a
    file therefore keeps its charges unmodelled and says so, rather than shipping an array that
    is two-thirds source data and one-third invention.

    The type symbol's own suffix (``Fe3+``) is *not* a second source of charge — it is an
    identifier that conventionally encodes one, and promoting a spelling to a physical quantity
    is interpretation, not reading. It is used here only to check the file against itself; a
    disagreement is reported and the explicitly declared number wins, because
    ``_atom_type_oxidation_number`` is the tag CIF defines for stating a charge.
    """
    if not oxidation_numbers:
        return None, []
    if types is None:
        return None, [
            ParseIssue(
                severity="warning",
                code="CIF_OXIDATION_NUMBERS_UNJOINED",
                message=(
                    f"file declares oxidation numbers for {sorted(oxidation_numbers)} but its "
                    "_atom_site loop carries no _atom_site_type_symbol column to join them to, "
                    "so electronic.charges was left unset rather than assigned by guesswork"
                ),
                location=f"line {line}",
            )
        ]

    issues: list[ParseIssue] = []
    # A site whose type symbol is '?' or '.' has nothing to join on, so it counts as undeclared
    # by the same reasoning: it too would need a fill value.
    site_types = [t.strip() if (t := types[i]) is not None else None for i in site_of]
    undeclared = sorted(
        "(unknown)" if t is None else t for t in set(site_types) if t not in oxidation_numbers
    )
    if undeclared:
        return None, [
            ParseIssue(
                severity="warning",
                code="CIF_PARTIAL_OXIDATION_NUMBERS",
                message=(
                    f"file declares oxidation numbers for {sorted(oxidation_numbers)} but not "
                    f"for atom type(s) {undeclared}, which its sites also use. electronic.charges "
                    "holds one value per atom, so a partial declaration cannot fill it without "
                    "asserting a charge for the remaining atoms; the field was left unset and "
                    "the declared numbers stay verbatim in simulation.extra"
                ),
                location=f"line {line}",
            )
        ]

    # Past the `undeclared` guard every site type is a symbol the oxidation loop declares, so the
    # Optionals are gone; rebinding says so once instead of asserting it at each use.
    joined = [t for t in site_types if t is not None]
    for symbol in sorted(set(joined)):
        spelled = charge_of_type_symbol(symbol)
        declared = oxidation_numbers[symbol]
        if spelled is not None and spelled != declared:
            issues.append(
                ParseIssue(
                    severity="warning",
                    code="CIF_OXIDATION_NUMBER_DISAGREES_WITH_SYMBOL",
                    message=(
                        f"atom type {symbol!r} spells charge {spelled:+g} in its type symbol but "
                        f"_atom_type_oxidation_number declares {declared:+g}. The declared number "
                        "was used, since that is the tag CIF defines for stating a charge; the "
                        "raw symbol is preserved per-atom under 'cif:type_symbol'"
                    ),
                    location=f"line {line}",
                )
            )

    return np.asarray([oxidation_numbers[symbol] for symbol in joined], dtype=float), issues


def _coordinates(loop: CifLoop, coord_tags: tuple[str, str, str]) -> tuple[np.ndarray, set[str]]:
    """The N×3 coordinate array, plus the set of tags that carried a standard uncertainty."""
    columns = []
    uncertain: set[str] = set()
    for tag in coord_tags:
        column = loop.column(tag)
        assert column is not None  # guaranteed by validate_atom_sites
        values = []
        for row, raw in enumerate(column):
            if raw is None:
                raise _error(
                    "CIF_MISSING_COORDINATE",
                    f"{tag} is unknown ('?' or '.') for atom site {row + 1}; a position "
                    "cannot be left absent for an atom that exists (Part 2 §3.3)",
                    location=f"line {loop.line}",
                )
            if has_uncertainty(raw):
                uncertain.add(tag)
            values.append(parse_number(raw, tag=tag, line=loop.line))
        columns.append(values)
    return np.asarray(columns, dtype=float).T, uncertain


def _carried_columns(loop: CifLoop) -> dict[str, Any]:
    """Every ``_atom_site`` column with no canonical home, verbatim under a ``cif:`` key.

    This is what keeps a tag this version does not model — occupancy above all (Part 3 §3 n.11),
    but also Wyckoff symbols, displacement parameters, and the site label (``Zn1``, whose index
    the element symbol alone does not carry) — from being silently lost while M19 is unwritten.

    Values are handed over as the source spelled them; the schema's ``custom_per_atom`` union
    then stores a wholly-numeric column as a float array and anything else as strings. That
    coercion is value-preserving (``"1.000"`` → ``1.0``) and applies no CIF-specific meaning,
    which is the line that matters: this layer never *interprets* a tag it does not model.
    """
    # `Any` rather than the schema's per-atom union: that alias is private, and the union is
    # resolved by pydantic at construction (numeric column -> array, otherwise strings).
    carried: dict[str, Any] = {}
    for index, tag in enumerate(loop.tags):
        if tag in _CONSUMED_SITE_TAGS:
            continue
        carried[f"cif:{tag.lstrip('_')}"] = [row[index] for row in loop.rows]
    return carried


def _carried_pairs(block: CifBlock) -> tuple[dict[str, str], list[str]]:
    """Block-level tag→value pairs with no canonical field, verbatim under ``cif:`` keys.

    Bibliographic and free-text tags (authors, journal, chemical name, publication year) have no
    home in a schema describing atoms and cells, and dropping them would be exactly the silent
    loss this project exists to prevent (Part 3 §3 n.9).
    """
    # The space-group *name* tags are excluded because they are mapped to cell.space_group;
    # carrying them here as well would duplicate one source fact in two canonical places, and a
    # later exporter reading both would have to decide which one wins.
    consumed = {
        *(t.lower() for t in CELL_LENGTH_TAGS),
        *(t.lower() for t in CELL_ANGLE_TAGS),
        *(t.lower() for t in SPACE_GROUP_NAME_TAGS),
    }
    extra: dict[str, str] = {}
    carried: list[str] = []
    for tag, value in block.pairs.items():
        if tag in consumed or value is None:
            continue
        extra[f"cif:{tag.lstrip('_')}"] = value
        carried.append(tag)
    return extra, carried


__all__ = [
    "CHARGE_SCHEME",
    "CHARGE_SCHEME_KEY",
    "FRACT_TAGS",
    "OCCUPANCY_KEY",
    "build",
    "charge_of_type_symbol",
    "element_of",
    "lattice_from_parameters",
]
