"""Symmetry-operation strings → affine operations (Part 3 §3 n.13, M18 deliverable 1).

A stage-3 sibling of ``_validate``: it reads what the *file declares* and imports nothing from
``xtalate.schema``. Expanding a declared operation list is reading the file as the standard
defines it — a format-defined fact, not computed symmetry. The Non-Goal forbids *deriving*
symmetry from coordinates; it does not forbid honouring operations the file states outright.

**Operations are exact rationals, not floats.** A CIF translation is written ``1/3``, ``2/3``,
``1/2`` — values whose binary expansion never terminates. Carrying them as floats would make
a site generated by ``x+1/3`` land 1e-16 away from where the same site generated by ``x-2/3``
lands, so the special-position merge in expansion would be comparing rounding noise against a
physical threshold. :class:`~fractions.Fraction` keeps ``1/3 + 1/3 + 1/3 == 1`` exactly, and
the conversion to float happens once, at the end. This is the same reasoning that put exact
trigonometry behind the standard cell angles in ``_build.lattice_from_parameters``.

An operation this module cannot read is a :class:`ParseError`, never a skipped operation: a
dropped operation is a fraction of the physical atoms, which is silently wrong stoichiometry in
every downstream conversion (n.13's own rejected alternative).
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from fractions import Fraction

from xtalate.sdk import ParseError, ParseIssue

_AXES = ("x", "y", "z")

# One signed term of a component: an optional coefficient, an optional variable, an optional
# divisor. Covers every spelling real files use — "x", "-y", "+1/2", "2x", "x/2", "0.5",
# "-1/4" — and, by requiring the whole term to match, rejects the ones they do not.
_TERM = re.compile(r"^(?P<coeff>\d+(?:\.\d+)?)?\*?(?P<var>[xyz])?(?:/(?P<divisor>\d+(?:\.\d+)?))?$")
# Split a component into signed terms while keeping each sign attached to its term.
_SIGNED_TERM = re.compile(r"[+-]?[^+-]+")


def _error(message: str, *, line: int) -> ParseError:
    return ParseError(
        [
            ParseIssue(
                severity="error",
                code="CIF_MALFORMED_SYMOP",
                message=message,
                location=f"line {line}",
            )
        ]
    )


@dataclass(frozen=True)
class SymmetryOperation:
    """One declared symmetry operation, as an exact affine map on fractional coordinates.

    ``rotation`` is the 3×3 matrix in row-major order (row *i* gives the output component *i*
    in terms of the input x, y, z) and ``translation`` the added vector. ``text`` is the source
    spelling, kept verbatim so provenance can carry what the file actually said rather than a
    round-tripped rendering of what this module understood it to mean.
    """

    rotation: tuple[tuple[Fraction, Fraction, Fraction], ...]
    translation: tuple[Fraction, Fraction, Fraction]
    text: str

    @property
    def is_identity(self) -> bool:
        return self.rotation == _IDENTITY_ROTATION and self.translation == _ZERO_TRANSLATION

    def apply(
        self, coordinate: tuple[Fraction, Fraction, Fraction]
    ) -> tuple[Fraction, Fraction, Fraction]:
        """Map one exact fractional coordinate through this operation."""
        return tuple(  # type: ignore[return-value]
            sum(
                (self.rotation[i][j] * coordinate[j] for j in range(3)),
                start=self.translation[i],
            )
            for i in range(3)
        )


_ONE, _ZERO = Fraction(1), Fraction(0)
_IDENTITY_ROTATION: tuple[tuple[Fraction, Fraction, Fraction], ...] = (
    (_ONE, _ZERO, _ZERO),
    (_ZERO, _ONE, _ZERO),
    (_ZERO, _ZERO, _ONE),
)
_ZERO_TRANSLATION = (_ZERO, _ZERO, _ZERO)

IDENTITY = SymmetryOperation(
    rotation=_IDENTITY_ROTATION, translation=_ZERO_TRANSLATION, text="x,y,z"
)


def parse_symop(text: str, *, line: int) -> SymmetryOperation:
    """Parse one ``'x, y+1/2, -z'`` operation string into an affine operation.

    Raises ``CIF_MALFORMED_SYMOP`` for anything it cannot read exactly, including an operation
    whose rotation part is not a crystallographic one (determinant other than ±1). That last
    check is worth its weight: it is what separates a genuine operation from a typo such as
    ``2x, y, z``, which parses term-by-term but maps the lattice onto a sublattice and would
    generate atoms at positions the crystal does not have.
    """
    stripped = text.strip().strip("'\"").strip()
    components = stripped.split(",")
    if len(components) != 3:
        raise _error(
            f"symmetry operation {text!r} has {len(components)} comma-separated component(s), "
            "not the three an x,y,z triplet requires",
            line=line,
        )

    rotation: list[tuple[Fraction, Fraction, Fraction]] = []
    translation: list[Fraction] = []
    for axis, component in zip(_AXES, components, strict=True):
        row, shift = _parse_component(component, axis=axis, source=text, line=line)
        rotation.append(row)
        translation.append(shift)

    determinant = _determinant(rotation)
    if abs(determinant) != 1:
        raise _error(
            f"symmetry operation {text!r} has rotation determinant {determinant}, not ±1; it is "
            "not a crystallographic operation and would generate sites the lattice does not have",
            line=line,
        )
    return SymmetryOperation(
        rotation=tuple(rotation),
        translation=(translation[0], translation[1], translation[2]),
        text=text.strip().strip("'\"").strip(),
    )


def parse_symops(texts: list[str], *, line: int) -> list[SymmetryOperation]:
    """Parse a declared operation loop, preserving order and rejecting an empty list.

    Order is preserved because ``parse_notes`` reports per-site multiplicities against the
    operation list as the file wrote it; a reordered list would make that report unverifiable
    against the source.
    """
    if not texts:
        raise _error(
            "the symmetry-operation loop declares no operations; a file that carries the loop "
            "at all must say which operations apply",
            line=line,
        )
    return [parse_symop(text, line=line) for text in texts]


def _parse_component(
    component: str, *, axis: str, source: str, line: int
) -> tuple[tuple[Fraction, Fraction, Fraction], Fraction]:
    """One component of the triplet → its rotation row and its translation entry."""
    text = re.sub(r"\s+", "", component).lower()
    if not text:
        raise _error(f"symmetry operation {source!r} has an empty {axis} component", line=line)

    row = [Fraction(0), Fraction(0), Fraction(0)]
    shift = Fraction(0)
    consumed = 0
    for match in _SIGNED_TERM.finditer(text):
        term = match.group()
        consumed += len(term)
        sign = Fraction(-1) if term.startswith("-") else Fraction(1)
        body = term.lstrip("+-")
        parsed = _TERM.match(body)
        if parsed is None or (parsed.group("coeff") is None and parsed.group("var") is None):
            raise _error(
                f"symmetry operation {source!r} has an unreadable term {term!r} in its {axis} "
                "component; operations are never partially applied, so the file is refused "
                "rather than expanded with an operation this parser guessed at",
                line=line,
            )
        magnitude = Fraction(parsed.group("coeff") or 1)
        divisor = parsed.group("divisor")
        if divisor is not None:
            if Fraction(divisor) == 0:
                raise _error(
                    f"symmetry operation {source!r} divides by zero in its {axis} component",
                    line=line,
                )
            magnitude /= Fraction(divisor)
        value = sign * magnitude
        variable = parsed.group("var")
        if variable is None:
            shift += value
        else:
            row[_AXES.index(variable)] += value

    if consumed != len(text):
        # finditer skipped something — a stray character the term grammar never saw.
        raise _error(
            f"symmetry operation {source!r} has unreadable characters in its {axis} component "
            f"({component.strip()!r})",
            line=line,
        )
    return (row[0], row[1], row[2]), shift


def _determinant(rotation: list[tuple[Fraction, Fraction, Fraction]]) -> Fraction:
    (a, b, c), (d, e, f), (g, h, i) = rotation
    return a * (e * i - f * h) - b * (d * i - f * g) + c * (d * h - e * g)


__all__ = ["IDENTITY", "SymmetryOperation", "parse_symop", "parse_symops"]
