"""H5MD golden fidelity (M74-S4; Part 8 §3).

Each case's parse is diffed against its hand-verified ``expected.canonical.json``. Because H5MD is a
binary HDF5 container, the fixtures cannot be authored by hand — they are regenerated by
``tests/golden/h5md/_generate.py`` from raw ``h5py`` groups built out of exact, hand-chosen values
(HDF5 object times pinned off so the bytes are reproducible), so the expectation remains external
truth rather than a blind snapshot. The generator uses raw ``h5py`` rather than ``exporters.h5md``
on purpose: a golden written by the exporter would only prove the two components agree, not that the
parser reads what the file actually holds.

The three anchors cover the field map on canonical units (``co2-nvt-3frame``), the variable-N read
mechanism on a committed binary file (``gcmc-variable-n-3frame``), and the time-dependent 3x3 box
reader (``npt-triclinic-2frame``). Unit laundering and torn-tail recovery are pinned in
``tests/parsers/test_h5md_laundering.py``; the identity round-trip through the exporter lives in
``tests/exporters/test_h5md.py``.
"""

from __future__ import annotations

import io
from pathlib import Path

import numpy as np
import pytest

from tests._format_helpers import assert_matches_golden
from xtalate.parsers.h5md import make_h5md_parser
from xtalate.schema import CanonicalObject

GOLDEN = Path(__file__).parent / "h5md"
CASES = ["co2-nvt-3frame", "gcmc-variable-n-3frame", "npt-triclinic-2frame"]


def _source(case: str) -> bytes:
    return (GOLDEN / case / "sample.h5").read_bytes()


def _parse(case: str) -> CanonicalObject:
    return make_h5md_parser().parse(io.BytesIO(_source(case)), filename="sample.h5").canonical


@pytest.mark.parametrize("case", CASES)
def test_parse_matches_golden(case: str) -> None:
    expected = (GOLDEN / case / "expected.canonical.json").read_text()
    assert_matches_golden(_parse(case), expected)


def test_constant_n_case_carries_every_mapped_field() -> None:
    """The all-fields anchor proves nothing the source stated is laundered away: per-frame
    positions/velocities/forces/charges, fixed masses, a cuboid box + pbc, and a per-frame energy
    all survive, in canonical units (nothing converted)."""
    obj = _parse("co2-nvt-3frame")
    assert obj.frame_count == 3
    frame = obj.frames[0]
    assert frame.atoms.symbols == ["C", "O", "O"]
    assert frame.atoms.masses is not None
    np.testing.assert_allclose(frame.atoms.masses, [12.011, 15.999, 15.999])
    assert frame.cell is not None and frame.cell.pbc == (True, True, True)
    assert frame.dynamics.velocities is not None
    assert frame.dynamics.forces is not None
    assert frame.electronic.charges is not None
    assert frame.electronic.total_energy == -100.0
    # Canonical units in, canonical units recorded — the file declared them, nothing was assumed.
    assert obj.provenance.source_units["positions"] == "Angstrom"


def test_variable_n_case_reads_each_frame_at_its_own_count() -> None:
    """The variable-N anchor: 2, then 3, then 4 atoms read natively (P3), a non-energy observable
    carried to custom_per_frame, and the energy series mapped to total_energy."""
    obj = _parse("gcmc-variable-n-3frame")
    assert [len(fr.atoms.symbols) for fr in obj.frames] == [2, 3, 4]
    assert obj.frames[2].atoms.symbols == ["Ar", "Ar", "Ar", "Ar"]
    assert obj.frames[0].atoms.masses is None  # the source stated none (P3)
    series = np.asarray(obj.user_metadata.custom_per_frame["h5md:temperature"])
    np.testing.assert_allclose(series, [300.0, 300.0, 300.0])
    assert [fr.electronic.total_energy for fr in obj.frames] == [-5.0, -7.5, -10.0]


def test_time_dependent_box_varies_per_frame() -> None:
    """The time-dependent-box anchor: a cell that shears to triclinic between frames, read from a
    time-dependent box/edges group with a full 3x3 matrix per step."""
    obj = _parse("npt-triclinic-2frame")
    c0, c1 = obj.frames[0].cell, obj.frames[1].cell
    assert c0 is not None and c1 is not None
    np.testing.assert_allclose(c0.lattice_vectors, np.diag([5.43, 5.43, 5.43]))
    np.testing.assert_allclose(
        c1.lattice_vectors, [[5.50, 0.0, 0.0], [0.10, 5.50, 0.0], [0.0, 0.0, 5.60]]
    )
