"""ASE ``.db`` golden fidelity (M55-S1; Part 8 §3).

Each case's parse is diffed against its hand-verified ``expected.canonical.json``. Because ``.db``
is ASE's binary SQLite container, the fixtures cannot be authored by hand — they are regenerated by
``tests/golden/ase_db/_generate.py`` from ``Atoms`` built out of exact, hand-chosen values (with
ASE's non-deterministic row metadata — ``uuid4``, wall-clock timestamps, ``$USER`` — pinned so the
bytes are reproducible), so the expectation remains external truth rather than a blind snapshot.

A single ``.db`` row is one Canonical Object, never a trajectory: *a dataset is aggregation, not a
new model.* Multi-row datasets refuse on this single-file path (``ASEDB_MULTIPLE_ROWS``) and fan
out under ``--batch`` (M55-S3); they are deliberately absent here. The identity round-trip through
the exporter lands with the ``ase_db`` write side (M55-S2), so this parser-only slice pins the read
fidelity and the laundering rules only.
"""

from __future__ import annotations

import io
from pathlib import Path

import numpy as np
import pytest

from tests._format_helpers import assert_matches_golden
from xtalate.parsers.ase_db import make_ase_db_parser
from xtalate.schema import CanonicalObject, Constraint

GOLDEN = Path(__file__).parent / "ase_db"
CASES = ["single-row-labeled", "rich-key-value"]


def _source(case: str) -> bytes:
    return (GOLDEN / case / "sample.db").read_bytes()


def _parse(case: str) -> CanonicalObject:
    return make_ase_db_parser().parse(io.BytesIO(_source(case)), filename="sample.db").canonical


@pytest.mark.parametrize("case", CASES)
def test_parse_matches_golden(case: str) -> None:
    expected = (GOLDEN / case / "expected.canonical.json").read_text()
    assert_matches_golden(_parse(case), expected)


def test_rich_case_carries_every_mapped_field() -> None:
    """The all-fields anchor exists to prove nothing was laundered away that the source *did* state:
    a present cell + pbc, source-written masses, velocities, forces, a fixed_atoms constraint, an
    energy, and the per-row key-value pair all survive."""
    obj = _parse("single-row-labeled")
    assert obj.trajectory is None
    frame = obj.frames[0]
    assert frame.cell is not None and frame.cell.pbc == (True, True, True)
    assert frame.atoms.masses is not None
    np.testing.assert_allclose(frame.atoms.masses, [12.011, 15.999])
    assert frame.dynamics.velocities is not None
    assert frame.dynamics.forces is not None
    assert frame.dynamics.constraints == [
        Constraint(kind="fixed_atoms", atom_indices=[0], parameters={})
    ]
    assert frame.electronic.total_energy == -5.0
    assert obj.user_metadata.custom_global["ase_db:label"] == "co-relaxed"


def test_minimal_case_launders_every_ase_default_to_absence() -> None:
    """The minimal molecule proves the laundering rules on a committed file: ASE's manufactured
    cell / masses / momenta / empty-constraints defaults are all absence, a single row carries no
    trajectory (P3), yet the per-row key-value pairs still carry verbatim (carry, never
    interpret)."""
    obj = _parse("rich-key-value")
    assert obj.trajectory is None
    frame = obj.frames[0]
    assert frame.cell is None
    assert frame.atoms.masses is None
    assert frame.dynamics.velocities is None
    assert frame.dynamics.constraints is None
    assert frame.electronic.total_energy is None
    assert obj.user_metadata.custom_global["ase_db:kind"] == "water"
