"""ASE ``.traj`` golden fidelity (M14C; Part 8 §3).

Each case's parse is diffed against its hand-verified ``expected.canonical.json``. Because ``.traj``
is ASE's binary ULM container, the fixtures cannot be authored by hand — they are regenerated by
``tests/golden/ase_traj/_generate.py`` from ``Atoms`` built out of exact, hand-chosen values, so the
expectation remains external truth (every number is verifiable against that generator) rather than a
blind snapshot of parser output.

The identity round-trip runs **through the streaming path** (``parse`` is defined as
``materialize(parse_stream(...))``), which is what pins the claim that the streamed and whole-file
readings agree on the committed fixtures, not only on the synthetic unit cases.
"""

from __future__ import annotations

import io
from pathlib import Path

import numpy as np
import pytest

from tests._format_helpers import assert_matches_golden, assert_scientifically_equal
from xtalate.exporters.ase_traj import make_ase_traj_exporter
from xtalate.parsers.ase_traj import make_ase_traj_parser
from xtalate.schema import CanonicalObject, Constraint
from xtalate.sdk.streaming import materialize

GOLDEN = Path(__file__).parent / "ase_traj"
CASES = ["co-relax-3frame", "water-single-molecule"]


def _source(case: str) -> bytes:
    return (GOLDEN / case / "relax.traj").read_bytes()


def _parse(case: str) -> CanonicalObject:
    return make_ase_traj_parser().parse(io.BytesIO(_source(case)), filename="relax.traj").canonical


@pytest.mark.parametrize("case", CASES)
def test_parse_matches_golden(case: str) -> None:
    expected = (GOLDEN / case / "expected.canonical.json").read_text()
    assert_matches_golden(_parse(case), expected)


@pytest.mark.parametrize("case", CASES)
def test_streamed_parse_matches_golden(case: str) -> None:
    """The streamed reading must match the *same* external-truth expectation the whole-file one
    does — not merely match the whole-file reading (which would be self-consistent by construction,
    since ``parse`` is defined through ``parse_stream``)."""
    expected = (GOLDEN / case / "expected.canonical.json").read_text()
    stream = make_ase_traj_parser().parse_stream(io.BytesIO(_source(case)), filename="relax.traj")
    obj, _ = materialize(stream)
    assert_matches_golden(obj, expected)


@pytest.mark.parametrize("case", CASES)
def test_identity_roundtrip_through_the_streaming_path(case: str) -> None:
    """``.traj → Canonical → .traj → Canonical′`` agrees on all scientific content (Part 3 §3)."""
    original = _parse(case)
    buf = io.BytesIO()
    make_ase_traj_exporter().export(original, buf)
    back = make_ase_traj_parser().parse(io.BytesIO(buf.getvalue()), filename="relax.traj").canonical
    assert_scientifically_equal(original, back)


def test_rich_case_carries_every_mapped_field() -> None:
    """The all-fields anchor exists to prove nothing was laundered away that the source *did* state:
    a present cell, source-written masses, unit-converted velocities, forces, a fixed_atoms
    constraint, an energy, and the per-frame ``step`` all survive."""
    obj = _parse("co-relax-3frame")
    assert obj.trajectory is not None
    frame = obj.frames[0]
    assert frame.cell is not None and frame.cell.pbc == (True, True, True)
    assert frame.atoms.masses is not None
    np.testing.assert_allclose(frame.atoms.masses, [12.011, 15.999])
    assert frame.dynamics.velocities is not None
    assert frame.dynamics.forces is not None
    assert frame.dynamics.constraints == [
        Constraint(kind="fixed_atoms", atom_indices=[0], parameters={})
    ]
    assert frame.electronic.total_energy == -5.0
    step = np.asarray(obj.user_metadata.custom_per_frame["ase_traj:step"], dtype=float)
    np.testing.assert_allclose(step, [0.0, 1.0, 2.0])


def test_minimal_case_launders_every_ase_default_to_absence() -> None:
    """The minimal molecule proves the laundering rules on a committed file: ASE's manufactured
    cell / masses / momenta / empty-constraints defaults are all absence, and a single frame carries
    no trajectory (P3)."""
    obj = _parse("water-single-molecule")
    assert obj.trajectory is None
    frame = obj.frames[0]
    assert frame.cell is None
    assert frame.atoms.masses is None
    assert frame.dynamics.velocities is None
    assert frame.dynamics.constraints is None
    assert frame.electronic.total_energy is None
