"""DeePMD ``.npy`` golden fidelity (v1.5 M56-S1; Part 8 §3).

Each case's parse is diffed against its hand-verified ``expected.canonical.json``. Because a
DeePMD system is a **directory** of NumPy files, the fixtures cannot be authored by hand —
they are regenerated by ``tests/golden/deepmd_npy/_generate.py`` from exact, hand-chosen
values (with the virial hand-computed from a declared stress + cell via the documented
stress·volume relation), so the expectation remains external truth rather than a blind
snapshot. One DeePMD system is one Canonical Object, never a dataset: multi-set *frames* are
one trajectory; multi-*system* grouping is the batch surface (M56-S3), deliberately absent
here.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest

from tests._format_helpers import assert_matches_golden
from tests.golden.deepmd_npy._systems import write_system
from xtalate.parsers.deepmd_npy import make_deepmd_npy_parser
from xtalate.schema import CanonicalObject
from xtalate.sdk import ParseError

GOLDEN = Path(__file__).parent / "deepmd_npy"
CASES = ["labeled-single-set", "multi-set", "no-type-map", "virial-labeled"]


def _source_files(case: str) -> dict[str, bytes]:
    root = GOLDEN / case / "system"
    return {
        path.relative_to(root).as_posix(): path.read_bytes()
        for path in sorted(root.rglob("*"))
        if path.is_file()
    }


def _parse(case: str) -> CanonicalObject:
    parser = make_deepmd_npy_parser()
    files = _source_files(case)
    if case == "no-type-map":
        # The committed source deliberately lacks type_map.raw (the recoverable
        # DEEPMD_MISSING_TYPE_MAP); the expectation is the recovered object, resolved here by
        # the existing missing_species scenario exactly as `--recover missing_species=species_map,
        # species=O H` drives it.
        return parser.parse_recover(
            b"",
            filename="system",
            hint="supply_species",
            choice="species_map",
            parameters={"species": "O H", "directory_files": files},
            recovery_context={},
        ).canonical
    return parser.parse_dir(files, dirname="system").canonical


@pytest.mark.parametrize("case", CASES)
def test_parse_matches_golden(case: str) -> None:
    expected = (GOLDEN / case / "expected.canonical.json").read_text()
    assert_matches_golden(_parse(case), expected)


def test_labeled_anchor_carries_every_mapped_field() -> None:
    obj = _parse("labeled-single-set")
    frame = obj.frames[0]
    assert obj.trajectory is None
    assert frame.cell is not None and frame.cell.pbc == (True, True, True)
    assert frame.atoms.symbols == ["O", "H", "H"]
    assert frame.electronic.total_energy == -14.0
    assert frame.atoms.positions is not None
    np.testing.assert_allclose(
        np.asarray(frame.atoms.positions),
        np.array([[0, 0, 0], [0.96, 0, 0], [-0.24, 0.93, 0]], dtype=np.float64),
    )
    # The source numbering carries verbatim (type_map "O H" / type.raw "0 1 1" — not
    # first-appearance-collapsed), the exporter's byte-faithful inverse.
    assert obj.user_metadata.custom_global["deepmd_npy:type_map"] == ["O", "H"]
    assert obj.user_metadata.custom_global["deepmd_npy:type_indices"] == [0, 1, 1]


def test_multi_set_case_is_one_concatenated_trajectory_with_the_partition_reported() -> None:
    parser = make_deepmd_npy_parser()
    files = _source_files("multi-set")
    result = parser.parse_dir(files, dirname="system")
    assert len(result.canonical.frames) == 3  # set.000 (2) + set.001 (1), sorted order
    assert result.canonical.trajectory is not None
    assert [i.code for i in result.issues] == ["DEEPMD_SET_PARTITION_DROPPED"]


def test_virial_case_maps_to_the_hand_computed_stress() -> None:
    frame = _parse("virial-labeled").frames[0]
    assert frame.electronic.stress is not None
    np.testing.assert_allclose(frame.electronic.stress, np.diag([0.01, 0.02, 0.03]), atol=1e-12)


def test_no_type_map_case_refuses_bare_and_resolves() -> None:
    parser = make_deepmd_npy_parser()
    files = _source_files("no-type-map")
    with pytest.raises(ParseError) as excinfo:
        parser.parse_dir(files, dirname="system")
    assert excinfo.value.issues[0].code == "DEEPMD_MISSING_TYPE_MAP"
    recovered = parser.parse_recover(
        b"",
        filename="system",
        hint="supply_species",
        choice="species_map",
        parameters={"species": "O H", "directory_files": files},
        recovery_context={},
    )
    assert recovered.canonical.frames[0].atoms.symbols == ["O", "H", "H"]
    # The regenerated fixtures must stay byte-reproducible from the same source values.
    rebuilt = write_system(
        coords=[[[0, 0, 0], [0.96, 0, 0], [-0.24, 0.93, 0]]],
        boxes=[[10.0, 0, 0, 0, 10.0, 0, 0, 0, 10.0]],
        energy=-14.0,
        forces=[[[0.05, 0.02, 0.0], [-0.03, 0.01, 0.0], [-0.02, -0.03, 0.0]]],
        omit_type_map=True,
    )
    assert set(files) == set(rebuilt)
    for path in files:
        assert files[path] == rebuilt[path], f"{path} drifted from the generator's values"
